package com.lovevol.mysite.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.date
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id_label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer idLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id_category
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer idCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sketch
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String sketch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.image_path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id_content
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer idContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.date
     *
     * @return the value of article.date
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.date
     *
     * @param date the value for article.date
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id_label
     *
     * @return the value of article.id_label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getIdLabel() {
        return idLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id_label
     *
     * @param idLabel the value for article.id_label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setIdLabel(Integer idLabel) {
        this.idLabel = idLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id_category
     *
     * @return the value of article.id_category
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getIdCategory() {
        return idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id_category
     *
     * @param idCategory the value for article.id_category
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sketch
     *
     * @return the value of article.sketch
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sketch
     *
     * @param sketch the value for article.sketch
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setSketch(String sketch) {
        this.sketch = sketch == null ? null : sketch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.image_path
     *
     * @return the value of article.image_path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.image_path
     *
     * @param imagePath the value for article.image_path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id_content
     *
     * @return the value of article.id_content
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getIdContent() {
        return idContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id_content
     *
     * @param idContent the value for article.id_content
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setIdContent(Integer idContent) {
        this.idContent = idContent;
    }
}