package com.lovevol.mysite.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.type
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.discription
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.type
     *
     * @return the value of category.type
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.type
     *
     * @param type the value for category.type
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.discription
     *
     * @return the value of category.discription
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.discription
     *
     * @param discription the value for category.discription
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }
}