package com.lovevol.mysite.model;

public class EBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.bookname
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.id
     *
     * @return the value of ebook.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.id
     *
     * @param id the value for ebook.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.bookname
     *
     * @return the value of ebook.bookname
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.bookname
     *
     * @param bookname the value for ebook.bookname
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.description
     *
     * @return the value of ebook.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.description
     *
     * @param description the value for ebook.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.path
     *
     * @return the value of ebook.path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.path
     *
     * @param path the value for ebook.path
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}