package com.lovevol.mysite.model;

public class Label {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.idcategory
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer idcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.articlenum
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer articlenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.id
     *
     * @return the value of label.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.id
     *
     * @param id the value for label.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.name
     *
     * @return the value of label.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.name
     *
     * @param name the value for label.name
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.idcategory
     *
     * @return the value of label.idcategory
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getIdcategory() {
        return idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.idcategory
     *
     * @param idcategory the value for label.idcategory
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.description
     *
     * @return the value of label.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.description
     *
     * @param description the value for label.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.articlenum
     *
     * @return the value of label.articlenum
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getArticlenum() {
        return articlenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.articlenum
     *
     * @param articlenum the value for label.articlenum
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setArticlenum(Integer articlenum) {
        this.articlenum = articlenum;
    }
}