package com.lovevol.mysite.model;

public class Web {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web.we_burl
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String weBurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web.remark
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web.label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web.id
     *
     * @return the value of web.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web.id
     *
     * @param id the value for web.id
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web.we_burl
     *
     * @return the value of web.we_burl
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getWeBurl() {
        return weBurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web.we_burl
     *
     * @param weBurl the value for web.we_burl
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setWeBurl(String weBurl) {
        this.weBurl = weBurl == null ? null : weBurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web.description
     *
     * @return the value of web.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web.description
     *
     * @param description the value for web.description
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web.remark
     *
     * @return the value of web.remark
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web.remark
     *
     * @param remark the value for web.remark
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web.label
     *
     * @return the value of web.label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web.label
     *
     * @param label the value for web.label
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}