server:
  port: 8000

spring:
  profiles:
    active: env
  datasource:
    url: jdbc:mysql://localhost:3306/my_site_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 2000
        max-idle: 50
        max-wait: 2000
        min-idle: 50
    password: null
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

logging:
  level:
    root: info
  file: mysite.log

