package com.lovevol.mysite.dao;

import com.lovevol.mysite.model.EBook;
import com.lovevol.mysite.model.EBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface EBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    long countByExample(EBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int deleteByExample(EBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int insert(EBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int insertSelective(EBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    List<EBook> selectByExample(EBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    EBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") EBook record, @Param("example") EBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByExample(@Param("record") EBook record, @Param("example") EBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByPrimaryKeySelective(EBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByPrimaryKey(EBook record);
}