package com.lovevol.mysite.dao;

import com.lovevol.mysite.model.Web;
import com.lovevol.mysite.model.WebExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface WebMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    long countByExample(WebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int deleteByExample(WebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int insert(Web record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int insertSelective(Web record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    List<Web> selectByExample(WebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    Web selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") Web record, @Param("example") WebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByExample(@Param("record") Web record, @Param("example") WebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByPrimaryKeySelective(Web record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbg.generated Sat Jul 21 15:02:58 CST 2018
     */
    int updateByPrimaryKey(Web record);
}